config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  resources :bio, only: [:index]

  resources :hobbies, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bio_controller.rb
class BioController < ApplicationController
  def index
  end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bio/index.html.erb
<div class="birthday">
  <h4> Birthday: </h4>
<ul> Born on April 15, 1994 </ul> <br>
</div>
<div class="education"> <br>
    <h4> Education: </h4>
  <ul>Xaverian Brothers H.S., Westwood MA, 2008-2012 </ul>
  <ul>Providence College, Providence RI, B.S. Marketing, 2012-2016 </ul>
  <ul>Launch Academy, Boston MA, Fall 2016-Winter 2017 </ul> <br>
</div>
<div class="links"> <br>
<h4> Links: </h4>
  <ul> github.com/mmcderm8 </ul>
  <ul> linkedin.com/in/matthew-mcdermott </ul>
  <ul> twitter.com/theTRUEderm24 </ul>
  <ul> facebook.com/matt.mcdermott.1232 </ul>
  <ul> instagram.com/the_true_derm24 </ul>
</div>

app/views/hobbies/index.html.erb
<div class="interests">
  <h3> Technology, Cruises, Sports </h3><br>
  <h4> Technology: </h4>
  <p> I graduated from Launch Academy in the winter of 2017 in Boston, MA. Launch Academy was my first formal training in web development and it was an amazing experience.
  <p> While at Launch, I learned full stack development. The most rewarding aspect of Launch Academy was knowing what it takes to quickly learn different aspects of development.
  <p> The best part of coding in my mind is being able to debug issues that arise and solve problems on your own. It is such a rewarding process.
  <h4> Cruises: </h4>
  <p> When I'm not coding, Im generally researching my passion ever since I was a little kid, and that is cruising.
  <p> As of February of 2017, I have been on 23 cruises. The majority of those within the caribbean. I have also taken several cruises throughout the Mediterranean Sea.
  <p> Lines I have sailed include: Carnival, Norweigan, Celebrity, Disney and Royal Caribbean.
  <p> People ask me all the time why I cruise, and its hard to put into words, but a cruise is the best vacation for the entire family because there is so much to do.
  <p> I believe cruising is the best way to vacation because more than 75% of the world is water, so unless you are a well traveled Pope, you will miss out on so much.
  <h4> Sports: </h4>
  <p> When I am not coding or cruising, my love is sports.
  <p> While I am a major fan of all Boston sports, my favorite teams are the Bruins and Patriots
  <p> I purchased an 11 game ticket package for the '16-'17 season.
</div>

app/views/home/index.html.erb
<h1>Matthew McDermott</h1>

<p> <img src = "http://i.imgur.com/1kSt8F1.jpg"> </p>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Matt McDermott", home_index_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "My hobbies", hobbies_path %></li>
        <li><%= link_to "Bio", bio_index_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matthew McDermott</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>